import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import Providers from "@/lib/providers";
import Background from "../public/background.png";
import "@/styles/globals.css";

const ibm = IBM_Plex_Mono({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body
        style={{ backgroundImage: `url(${Background.src})` }}
        className={`${ibm.className} min-h-screen flex flex-col relative bg-black bg-repeat bg-fixed`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
